repos:
  #In case of depreciated code when repurposing from stackoverflow or similar
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.29.0
    hooks:
      - id: django-upgrade
    #Keep lockfile up to date
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.5
    hooks:
      - id: uv-lock
    #Linting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args:
          - --fix
    #Formatting
  - repo: https://github.com/psf/black-pre-commit-mirror.git
    rev: 25.9.0
    hooks:
      - id: black
    #HTML/CSS Linting
  - repo: https://github.com/rtts/djhtml
    rev: 3.0.10
    hooks:
      - id: djcss
        files: '^mousemetrics/.*\.css$'
        exclude: ".*/staticfiles/.*|.*/static/dist/.*"
    #Out of the box hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      #Filesystem
      - id: check-case-conflict
      - id: check-illegal-windows-names
        #Text formatting
      - id: end-of-file-fixer
      - id: trailing-whitespace
        #File checks
      - id: check-json
      - id: check-toml
      - id: check-yaml
        #Python
      - id: name-tests-test
        #Git
      - id: no-commit-to-branch
    #Type checking
  - repo: https://github.com/facebook/pyrefly-pre-commit
    rev: 0.50.1
    hooks:
      - id: pyrefly-check
        name: Pyrefly (type checking)
        pass_filenames: false
        entry: uv run pyrefly check
    #Pytest
  - repo: local
    hooks:
      - id: pytest-mouseapp
        name: pytest-check
        entry: uv run pytest
        language: system
        pass_filenames: false
    #Detect API Keys
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
        exclude: package.lock.json
